### ISSUE TITLE
com.kiuwan.importer.beans.File will fail to hash source code correctly on different JRE/OS combinations

### ISSUE THREAD

**Issue by fge** [kiuwan/thirdparty-report-importer#1]
The bug is here:

https://github.com/kiuwan/thirdparty-report-importer/blob/master/src/com/kiuwan/importer/beans/File.java#L66

If the code is run on the same file on two different JRE/OS environments where the file encoding differs, the generated MD5 sum will differ as well.

The source code should be hashed with a given encoding; for instance, `.getBytes("UTF-8")`.

**Comment by kiuwan** [comment]
Hi Francis. Thank you for reporting. We have just corrected right now.
