### ISSUE TITLE
Converting from ruby brakeman 

### ISSUE THREAD

**Issue by anquegi** [kiuwan/thirdparty-report-importer#8]
I generate the inform with ruby gem brakeman it works well, but when I try to create the output json file to kiuwan xml it allways give me Incorrect type:
```

java -cp kiuwan-thirdparty-report-importer-0.2.3.jar com.kiuwan.importer.Main BrakeMan kareman_kiuwan.json kiuwan_brakeman.xml
Incorrect Type.
```

**Comment by jsalado** [comment]
Hello there,

I think you are missing the -base-folder parameter required when translating Breakman results. Your command should look like this:
`java -cp kiuwan-thirdparty-report-importer-0.2.3.jar com.kiuwan.importer.Main BrakeMan brakeman.json  kiuwan_brakeman.xml -base-folder=c:\ruby_sources
`
Just substitute the names of the files and c:\ruby_sources by the folder with the ruby sources you analyzed with Breakman.

I hope this helps.

**Comment by anquegi** [comment]
I add the base-folder=, but I receive the same output

**Comment by jsalado** [comment]
Given your latest comment I just want to make sure you have to add -base-folder="C:\your source folder path\"

Notice the - before base-folder and that you need to specify the folder where your ruby source code starts. I have added the enclosing " in case your path has spaces.

Please confirm.

**Comment by anquegi** [comment]
Thanks for answering @jsalado , the path seems to be a windows machine, could be the problem use MAC OS X?

**Comment by jsalado** [comment]
No, it shouldn't be a problem. Just make sure you specify the absolute path to the source code folder. something like /homes/jsalado/myrubyproject/src

**Comment by anquegi** [comment]
But if that is case I get the error:

Brakeman works well

`brakeman -o brakeman_output.json`                                                                                                                                                     
```
Loading scanner...
Processing application in /Users/toni/src/
Processing gems...
[Notice] Detected Rails 3 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...ssed
Processing routes...
Processing templates...
Processing data flow in templates...
Processing models...
Processing controllers...
Processing data flow in controllers...
Indexing call sites...
Running checks in parallel...
 - CheckBasicAuth
 - CheckBasicAuthTimingAttack
 - CheckCrossSiteScripting
 - CheckContentTag
 - CheckCreateWith
 - CheckDefaultRoutes
 - CheckDeserialize
 - CheckDetailedExceptions
 - CheckDigestDoS
 - CheckDynamicFinders
 - CheckEscapeFunction
 - CheckEvaluation
 - CheckExecute
 - CheckFileAccess
 - CheckFileDisclosure
 - CheckFilterSkipping
 - CheckForgerySetting
 - CheckHeaderDoS
 - CheckI18nXSS
 - CheckJRubyXML
 - CheckJSONEncoding
 - CheckJSONParsing
 - CheckLinkTo
 - CheckLinkToHref
 - CheckMailTo
 - CheckMassAssignment
 - CheckMimeTypeDoS
 - CheckModelAttrAccessible
 - CheckModelAttributes
 - CheckModelSerialize
 - CheckNestedAttributes
 - CheckNestedAttributesBypass
 - CheckNumberToCurrency
 - CheckPermitAttributes
 - CheckQuoteTableName
 - CheckRedirect
 - CheckRegexDoS
 - CheckRender
 - CheckRenderDoS
 - CheckRenderInline
 - CheckResponseSplitting
 - CheckRouteDoS
 - CheckSafeBufferManipulation
 - CheckSanitizeMethods
 - CheckSelectTag
 - CheckSelectVulnerability
 - CheckSend
 - CheckSendFile
 - CheckSessionManipulation
 - CheckSessionSettings
 - CheckSimpleFormat
 - CheckSingleQuotes
 - CheckSkipBeforeFilter
 - CheckSQL
 - CheckSQLCVEs
 - CheckSSLVerify
 - CheckStripTags
 - CheckSymbolDoSCVE
 - CheckTranslateBug
 - CheckUnsafeReflection
 - CheckValidationRegex
 - CheckWithoutProtection
 - CheckXMLDoS
 - CheckYAMLParsing
Checks finished, collecting results...
Generating report...
Report saved in 'brakeman_output.json'
```

Then I try with my absolute path:
```

java -cp kiuwan-thirdparty-report-importer-0.2.3.jar com.kiuwan.importer.Main BrakeMan /Users/toni/src/brakeman_output.json /Users/toni/src/kiuwan_brakeman.xml -base-folder=/Users/toni/src/
Incorrect Type.
```

I do not know what to try, maybe is the java version

**Comment by jsalado** [comment]
@anquegi I found the problem... Sorry for the inconvenience, but it is a typo in the readme.md documentation. to run a BreakMan conversion you have to specify Breakman as the first argument NOT BreakMan as specified in the documentation.

I'll change the documentation and open a pull request.

Thanks for your patience.

**Comment by anquegi** [comment]
@jsalado Thanks a lot for finding the bug in the documentation, it worked:

```
java -cp kiuwan-thirdparty-report-importer-0.2.3.jar com.kiuwan.importer.Main Brakeman /Users/toni/src/11paths/P-antifraude/antifraud/brakeman_output.json /Users/toni/src/11paths/P-antifraude/antifraud/kiuwan_brakeman.xml -base-folder=/Users/toni/src/11paths/P-antifraude/antifraud/
File /Users/toni/src/11paths/P-antifraude/antifraud/kiuwan_brakeman.xml successfully generated.
```

Since you install the Brakeman gem with `gem install brakeman`, I will put the name 

> brakeman

Anyway thanks for helping

**Comment by jsalado** [comment]
You're welcome. Always glad to help
